'--------------------------------------------------------------------------------------------------------------------------------------------------
' (c) Copyright SeaChange
'
' File Name						:	EditScheduledReport_SchduleOptions_ReportFormatDropdown
' Description					:	Validate the Schedule Options Report Format.
' Author 						:   SeaChange
' Date 							:   22-08-2012
''--------------------------------------------------------------------------------------------------------------------------------------------------

'Start Test Case
executionController.startTestCase_w_TestCaseNumber "EditScheduledReport_SchduleOptions_ReportFormatDropdown", "SCR_New_TC_011"



 ivm.NavigateToMenu MENU_SCHEDULED_REPORTS
  wait 10
  
with ivm.page(ScheduledReports_Page)


			.webElement("ScheduledReports").assertExist "True"
			.webElement("ScheduledReports").assertStatus "Visible"
			
			.webTable("ScheduledReports").assertExist "True"
			.webTable("ScheduledReports_Header").assertExist "True"
			.webTable("ScheduledReports_Header").assertColumnExist "Report Name", "True"
			.webTable("ScheduledReports_Header").assertColumnExist "Schedule", "True"
			.webTable("ScheduledReports_Header").assertColumnExist "Next Report Scheduled", "True"
			.webTable("ScheduledReports_Header").assertColumnExist "Generated By", "True"
			.webTable("ScheduledReports_Header").assertColumnExist "Actions", "True"
			

end with
'Stop Test Case
executionController.stopTestCase_w_TestCaseNumber "ScheduleNewReport_SchduleOptions_ReportFormat", "SCR_New_TC_011"